#!/usr/bin/env node
/* Flattens the @import graph under src/ into single files. No dependencies, no bundler.

     npm run build                              → dist/nocturne.css + dist/tokens.css (prefix "ntn")
     nocturne-build --prefix cms --out <dir>    → <dir>/nocturne.css, tokens.css, nocturne.js, themes/*

   or from Node:

     import { build } from '@homestar9/nocturne-ui/build';
     await build({ prefix: 'cms', outDir: 'resources/kits/nocturne' });

   The prefix renames EVERY namespaced identifier: classes (.cms-card), tokens (--cms-accent),
   hooks (data-cms-open, and the matching dataset.cmsOpen in JS), events (cms:tabchange), the
   theme storage key and keyframe names. Source always spells the namespace "ntn", so a prefixed
   build is a whole-token rename of that spelling. */
import { readFile, writeFile, mkdir, readdir, realpath } from 'node:fs/promises';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const IMPORT = /^@import\s+url\(["']([^"')]+)["']\);?\s*$/;

/* Lowercase letters and digits only: data-{p}-x must map to dataset.{p}X in JS, which breaks
   on hyphens or capitals. */
export const PREFIX_PATTERN = /^[a-z][a-z0-9]*$/;
const SOURCE_PREFIX = 'ntn';

async function flatten(file, seen = new Set()) {
  const abs = resolve(file);
  if (seen.has(abs)) return '';
  seen.add(abs);
  const src = await readFile(abs, 'utf8');
  const out = [];
  for (const line of src.split('\n')) {
    const m = line.trim().match(IMPORT);
    if (!m) { out.push(line); continue; }
    if (/^https?:/.test(m[1])) { out.push(line); continue; }   // remote @imports stay
    out.push(await flatten(resolve(dirname(abs), m[1]), seen));
  }
  return out.join('\n');
}

/* CSS requires every @import to precede other rules — hoist the remote ones. */
function hoistRemoteImports(css) {
  const imports = [];
  const body = css.replace(/^@import\s+url\(["']https?:[^)]+\);?\s*$/gm, (m) => { imports.push(m.trim()); return ''; });
  return (imports.length ? imports.join('\n') + '\n\n' : '') + body.replace(/\n{3,}/g, '\n\n').trim() + '\n';
}

/**
 * Renames the source namespace to `prefix`: "ntn" → prefix, and "Ntn" (camelCase dataset keys)
 * → Prefix. A no-op for the default prefix.
 */
export function applyPrefix(text, prefix) {
  if (prefix === SOURCE_PREFIX) return text;
  const cap = prefix[0].toUpperCase() + prefix.slice(1);
  return text.replace(/ntn/g, prefix).replace(/Ntn/g, cap);
}

const banner = (name, version, prefix) => `/*! Nocturne ${name} v${version}${prefix === SOURCE_PREFIX ? '' : ` (prefix "${prefix}")`} — dark-first SaaS design system.
 *  Generated by scripts/build.mjs. Edit files in src/, never in dist/. */\n\n`;

/**
 * Builds Nocturne with the given namespace prefix.
 *
 * @param {object}   [options]
 * @param {string}   [options.prefix="ntn"]   Namespace for classes, tokens, hooks and events.
 * @param {string}   [options.outDir]         Output folder (default: the package's dist/).
 * @param {string[]} [options.include]        Any of "css", "js", "themes". Default: all three,
 *                                            except the plain `npm run build`, which writes CSS only.
 * @param {boolean}  [options.log=false]      Print one line per written file.
 * @returns {Promise<string[]>} Absolute paths of the files written.
 */
export async function build({ prefix = SOURCE_PREFIX, outDir = resolve(root, 'dist'), include = ['css', 'js', 'themes'], log = false } = {}) {
  if (typeof prefix !== 'string' || !PREFIX_PATTERN.test(prefix)) {
    throw new Error(`Nocturne: invalid prefix "${prefix}". Use lowercase letters and digits, starting with a letter (e.g. "cms").`);
  }
  const pkg = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8'));
  const out = resolve(outDir);
  const written = [];
  const write = async (rel, text) => {
    const file = join(out, rel);
    await mkdir(dirname(file), { recursive: true });
    await writeFile(file, text);
    written.push(file);
    if (log) console.log(`${rel}  ${(text.length / 1024).toFixed(1)} kB`);
  };

  if (include.includes('css')) {
    for (const [entry, name] of [['src/nocturne.css', 'nocturne.css'], ['src/tokens.css', 'tokens.css']]) {
      const css = hoistRemoteImports(await flatten(resolve(root, entry)));
      await write(name, banner(name, pkg.version, prefix) + applyPrefix(css, prefix));
    }
  }
  if (include.includes('js')) {
    await write('nocturne.js', applyPrefix(await readFile(resolve(root, 'js/nocturne.js'), 'utf8'), prefix));
  }
  if (include.includes('themes')) {
    for (const f of (await readdir(resolve(root, 'themes'))).filter((n) => n.endsWith('.css')).sort()) {
      await write(join('themes', f), applyPrefix(await readFile(resolve(root, 'themes', f), 'utf8'), prefix));
    }
  }
  return written;
}

/* ── CLI ─────────────────────────────────────────────────────────────────── */
function parseArgs(argv) {
  const opts = {};
  for (let i = 0; i < argv.length; i++) {
    const [flag, inline] = argv[i].split('=');
    const value = () => inline ?? argv[++i];
    if (flag === '--prefix') opts.prefix = value();
    else if (flag === '--out') opts.outDir = value();
    else if (flag === '--help' || flag === '-h') opts.help = true;
    else throw new Error(`Nocturne: unknown option "${argv[i]}". Try --help.`);
  }
  return opts;
}

async function isMain() {
  if (!process.argv[1]) return false;
  try { return pathToFileURL(await realpath(process.argv[1])).href === pathToFileURL(await realpath(fileURLToPath(import.meta.url))).href; }
  catch { return false; }
}

if (await isMain()) {
  try {
    const opts = parseArgs(process.argv.slice(2));
    if (opts.help) {
      console.log('Usage: nocturne-build [--prefix <name>] [--out <dir>]\n\n'
        + '  No options: rebuild the package\'s own dist/ CSS (prefix "ntn").\n'
        + '  --prefix  Namespace for classes, tokens, hooks and events (default "ntn").\n'
        + '  --out     Output folder. Writes nocturne.css, tokens.css, nocturne.js and themes/.');
    } else {
      // Plain `npm run build`: the package's own dist/ keeps its CSS-only layout.
      const cssOnly = opts.prefix === undefined && opts.outDir === undefined;
      await build({ ...opts, include: cssOnly ? ['css'] : undefined, log: true });
    }
  } catch (err) {
    console.error(err.message);
    process.exitCode = 1;
  }
}
