#!/usr/bin/env node
/* Flattens the @import graph under src/ into single files in dist/.
   No dependencies, no bundler — run: npm run build */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const IMPORT = /^@import\s+url\(["']([^"')]+)["']\);?\s*$/;

async function flatten(file, seen = new Set()) {
  const abs = resolve(file);
  if (seen.has(abs)) return '';
  seen.add(abs);
  const src = await readFile(abs, 'utf8');
  const out = [];
  for (const line of src.split('\n')) {
    const m = line.trim().match(IMPORT);
    if (!m) { out.push(line); continue; }
    if (/^https?:/.test(m[1])) { out.push(line); continue; }   // remote @imports stay
    out.push(await flatten(resolve(dirname(abs), m[1]), seen));
  }
  return out.join('\n');
}

/* CSS requires every @import to precede other rules — hoist the remote ones. */
function hoistRemoteImports(css) {
  const imports = [];
  const body = css.replace(/^@import\s+url\(["']https?:[^)]+\);?\s*$/gm, (m) => { imports.push(m.trim()); return ''; });
  return (imports.length ? imports.join('\n') + '\n\n' : '') + body.replace(/\n{3,}/g, '\n\n').trim() + '\n';
}

const banner = (name, version) => `/*! Nocturne ${name} v${version} — dark-first SaaS design system.
 *  Generated by scripts/build.mjs. Edit files in src/, never in dist/. */\n\n`;

const pkg = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8'));
await mkdir(resolve(root, 'dist'), { recursive: true });

for (const [entry, name] of [['src/nocturne.css', 'nocturne.css'], ['src/tokens.css', 'tokens.css']]) {
  const css = hoistRemoteImports(await flatten(resolve(root, entry)));
  await writeFile(resolve(root, 'dist', name), banner(name, pkg.version) + css);
  console.log('dist/' + name + '  ' + (css.length / 1024).toFixed(1) + ' kB');
}
