#!/usr/bin/env node
/* Flattens the @import graph under src/ into single files. No dependencies, no bundler.

     npm run build                              → dist/nocturne.css + dist/tokens.css (prefix "ntn")
     nocturne-build --prefix cms --out <dir>    → <dir>/nocturne.css, tokens.css, nocturne.js, themes/*

   or from Node:

     import { build } from '@homestar9/nocturne-ui/build';
     await build({ prefix: 'cms', outDir: 'resources/kits/nocturne' });

   The prefix renames EVERY namespaced identifier: classes (.cms-card), tokens (--cms-accent),
   hooks (data-cms-open, and the matching dataset.cmsOpen in JS), events (cms:tabchange), the
   theme storage key and keyframe names. Source always spells the namespace "ntn", so a prefixed
   build is a whole-token rename of that spelling. */
import { readFile, writeFile, mkdir, readdir, realpath } from 'node:fs/promises';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const IMPORT = /^@import\s+url\(["']([^"')]+)["']\);?\s*$/;

/* Lowercase letters and digits only: data-{p}-x must map to dataset.{p}X in JS, which breaks
   on hyphens or capitals. */
export const PREFIX_PATTERN = /^[a-z][a-z0-9]*$/;
const SOURCE_PREFIX = 'ntn';

async function flatten(file, seen = new Set()) {
  const abs = resolve(file);
  if (seen.has(abs)) return '';
  seen.add(abs);
  const src = await readFile(abs, 'utf8');
  const out = [];
  for (const line of src.split('\n')) {
    const m = line.trim().match(IMPORT);
    if (!m) { out.push(line); continue; }
    if (/^https?:/.test(m[1])) { out.push(line); continue; }   // remote @imports stay
    out.push(await flatten(resolve(dirname(abs), m[1]), seen));
  }
  return out.join('\n');
}

/* CSS requires every @import to precede other rules — hoist the remote ones. */
function hoistRemoteImports(css) {
  const imports = [];
  const body = css.replace(/^@import\s+url\(["']https?:[^)]+\);?\s*$/gm, (m) => { imports.push(m.trim()); return ''; });
  return (imports.length ? imports.join('\n') + '\n\n' : '') + body.replace(/\n{3,}/g, '\n\n').trim() + '\n';
}

/* Custom properties that belong to the MARKUP VOCABULARY rather than to the kit's design tokens.
   They follow the class prefix even when tokenPrefix differs, because any kit styling the same
   markup must read them:
     - state vars: written by nocturne.js (--ntn-tab-x, --ntn-slider-pct, --ntn-progress …),
       discovered from its setProperty('--ntn-…') calls so the list can't drift;
     - public knobs: set by consumers on a block to tune it. Listed here by hand. */
export const KNOBS = ['tree-indent'];
const STATE_VAR_CALL = /setProperty\(\s*['"]--ntn-([a-zA-Z0-9-]+)['"]/g;

/** Names (without the "--ntn-" part) of the custom properties that follow the class prefix. */
export async function vocabularyVars() {
  const js = await readFile(resolve(root, 'js/nocturne.js'), 'utf8');
  return new Set([...[...js.matchAll(STATE_VAR_CALL)].map((m) => m[1]), ...KNOBS]);
}

/**
 * Renames the source namespace in one pass. Custom properties go to `tokenPrefix` (design
 * tokens) or `prefix` (vocabulary vars); every other "ntn" (classes, data-ntn-* hooks, ntn:*
 * events, storage key, keyframes) goes to `prefix`, and "Ntn" (camelCase dataset keys) to the
 * capitalised prefix. A no-op when both prefixes are the default.
 */
export function applyPrefix(text, prefix, { tokenPrefix = prefix, vocab = new Set() } = {}) {
  if (prefix === SOURCE_PREFIX && tokenPrefix === SOURCE_PREFIX) return text;
  const cap = prefix[0].toUpperCase() + prefix.slice(1);
  return text.replace(/--ntn-([a-zA-Z0-9-]+)|ntn|Ntn/g, (match, name) => {
    if (name !== undefined) return `--${vocab.has(name) ? prefix : tokenPrefix}-${name}`;
    return match === 'Ntn' ? cap : prefix;
  });
}

const banner = (name, version, prefix, tokenPrefix) => `/*! Nocturne ${name} v${version}${prefix === SOURCE_PREFIX && tokenPrefix === SOURCE_PREFIX ? '' : ` (prefix "${prefix}", tokens "${tokenPrefix}")`} — dark-first SaaS design system.
 *  Generated by scripts/build.mjs. Edit files in src/, never in dist/. */\n\n`;

/**
 * Builds Nocturne with the given namespace prefix.
 *
 * @param {object}   [options]
 * @param {string}   [options.prefix="ntn"]   Namespace for classes, hooks, events and vocabulary vars.
 * @param {string}   [options.tokenPrefix]    Namespace for design tokens (default: same as prefix).
 *                                            Keep "ntn" to leave Nocturne's tokens visibly kit-owned
 *                                            while the markup vocabulary uses your own prefix.
 * @param {string}   [options.outDir]         Output folder (default: the package's dist/).
 * @param {string[]} [options.include]        Any of "css", "js", "themes". Default: all three,
 *                                            except the plain `npm run build`, which writes CSS only.
 * @param {boolean}  [options.log=false]      Print one line per written file.
 * @returns {Promise<string[]>} Absolute paths of the files written.
 */
export async function build({ prefix = SOURCE_PREFIX, tokenPrefix = prefix, outDir = resolve(root, 'dist'), include = ['css', 'js', 'themes'], log = false } = {}) {
  for (const [label, value] of [['prefix', prefix], ['tokenPrefix', tokenPrefix]]) {
    if (typeof value !== 'string' || !PREFIX_PATTERN.test(value)) {
      throw new Error(`Nocturne: invalid ${label} "${value}". Use lowercase letters and digits, starting with a letter (e.g. "cms").`);
    }
  }
  const vocab = await vocabularyVars();
  const rename = (text) => applyPrefix(text, prefix, { tokenPrefix, vocab });
  const pkg = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8'));
  const out = resolve(outDir);
  const written = [];
  const write = async (rel, text) => {
    const file = join(out, rel);
    await mkdir(dirname(file), { recursive: true });
    await writeFile(file, text);
    written.push(file);
    if (log) console.log(`${rel}  ${(text.length / 1024).toFixed(1)} kB`);
  };

  if (include.includes('css')) {
    for (const [entry, name] of [['src/nocturne.css', 'nocturne.css'], ['src/tokens.css', 'tokens.css']]) {
      const css = hoistRemoteImports(await flatten(resolve(root, entry)));
      await write(name, banner(name, pkg.version, prefix, tokenPrefix) + rename(css));
    }
  }
  if (include.includes('js')) {
    await write('nocturne.js', rename(await readFile(resolve(root, 'js/nocturne.js'), 'utf8')));
  }
  if (include.includes('themes')) {
    for (const f of (await readdir(resolve(root, 'themes'))).filter((n) => n.endsWith('.css')).sort()) {
      await write(join('themes', f), rename(await readFile(resolve(root, 'themes', f), 'utf8')));
    }
  }
  return written;
}

/* ── CLI ─────────────────────────────────────────────────────────────────── */
function parseArgs(argv) {
  const opts = {};
  for (let i = 0; i < argv.length; i++) {
    const [flag, inline] = argv[i].split('=');
    const value = () => inline ?? argv[++i];
    if (flag === '--prefix') opts.prefix = value();
    else if (flag === '--token-prefix') opts.tokenPrefix = value();
    else if (flag === '--out') opts.outDir = value();
    else if (flag === '--help' || flag === '-h') opts.help = true;
    else throw new Error(`Nocturne: unknown option "${argv[i]}". Try --help.`);
  }
  return opts;
}

async function isMain() {
  if (!process.argv[1]) return false;
  try { return pathToFileURL(await realpath(process.argv[1])).href === pathToFileURL(await realpath(fileURLToPath(import.meta.url))).href; }
  catch { return false; }
}

if (await isMain()) {
  try {
    const opts = parseArgs(process.argv.slice(2));
    if (opts.help) {
      console.log('Usage: nocturne-build [--prefix <name>] [--token-prefix <name>] [--out <dir>]\n\n'
        + '  No options: rebuild the package\'s own dist/ CSS (prefix "ntn").\n'
        + '  --prefix        Namespace for classes, hooks, events and state vars (default "ntn").\n'
        + '  --token-prefix  Namespace for design tokens (default: same as --prefix).\n'
        + '  --out           Output folder. Writes nocturne.css, tokens.css, nocturne.js and themes/.');
    } else {
      // Plain `npm run build`: the package's own dist/ keeps its CSS-only layout.
      const cssOnly = opts.prefix === undefined && opts.tokenPrefix === undefined && opts.outDir === undefined;
      await build({ ...opts, include: cssOnly ? ['css'] : undefined, log: true });
    }
  } catch (err) {
    console.error(err.message);
    process.exitCode = 1;
  }
}
